import 'package:equatable/equatable.dart';

/// Represents revenue data for a specific day.
class RevenueByDay extends Equatable {
  /// The date in string format (e.g., '2023-10-01').
  final String date;

  /// Total revenue generated on this day.
  final double revenue;

  /// Number of bookings made on this day.
  final int bookingCount;

  const RevenueByDay({required this.date, required this.revenue, required this.bookingCount});

  @override
  List<Object?> get props => [date, revenue, bookingCount];
}

/// Represents booking statistics for a specific club.
class BookingsByClub extends Equatable {
  /// Unique identifier of the club.
  final int clubId;

  /// Name of the club.
  final String clubName;

  /// Total number of bookings for this club.
  final int bookingCount;

  /// Total revenue generated by bookings for this club.
  final double revenue;

  const BookingsByClub({required this.clubId, required this.clubName, required this.bookingCount, required this.revenue});

  @override
  List<Object?> get props => [clubId, bookingCount];
}

/// Main admin statistics data class containing various metrics.
class AdminStats extends Equatable {
  /// Total revenue generated today.
  final double totalRevenueToday;

  /// Number of currently active bookings.
  final int activeBookings;

  /// Number of payments that are pending.
  final int pendingPayments;

  /// Total number of registered users.
  final int totalUsers;

  /// Number of users pending approval.
  final int pendingUsers;

  /// List of booking statistics by club.
  final List<BookingsByClub> bookingsByClub;

  /// List of revenue data by day.
  final List<RevenueByDay> revenueByDay;

  const AdminStats({
    required this.totalRevenueToday,
    required this.activeBookings,
    required this.pendingPayments,
    required this.totalUsers,
    required this.pendingUsers,
    required this.bookingsByClub,
    required this.revenueByDay,
  });

  @override
  List<Object?> get props => [totalRevenueToday, activeBookings, pendingPayments, totalUsers, pendingUsers];
}

/// Represents a club item for admin management.
class AdminClubItem extends Equatable {
  /// Unique identifier of the club.
  final int id;

  /// Name of the club.
  final String name;

  /// Location description of the club.
  final String location;

  /// Price per hour for computer usage.
  final int pricePerHour;

  /// Total number of computers available.
  final int totalComputers;

  /// Average rating of the club.
  final double rating;

  /// Whether the club is currently active.
  final bool isActive;

  /// Opening hour (24-hour format).
  final int openingHour;

  /// Closing hour (24-hour format).
  final int closingHour;

  /// Detailed address of the club (optional).
  final String? address;

  /// Latitude coordinate (optional).
  final double? latitude;

  /// Longitude coordinate (optional).
  final double? longitude;

  /// URL to the club's image (optional).
  final String? imageUrl;

  /// Total number of bookings for this club.
  final int bookingCount;

  /// Total revenue generated by this club.
  final double revenue;

  const AdminClubItem({
    required this.id, required this.name, required this.location,
    required this.pricePerHour, required this.totalComputers,
    required this.rating, required this.isActive,
    required this.openingHour, required this.closingHour,
    this.address, this.latitude, this.longitude, this.imageUrl,
    this.bookingCount = 0, this.revenue = 0,
  });

  @override
  List<Object?> get props => [id, name];
}

/// Represents a user item for admin management.
class AdminUserItem extends Equatable {
  /// Unique identifier of the user.
  final int id;

  /// Username of the user.
  final String username;

  /// Email address of the user.
  final String email;

  /// Phone number of the user.
  final String phone;

  /// Whether the user account is approved.
  final bool isApproved;

  /// Total number of bookings made by the user.
  final int bookingCount;

  /// Total amount spent by the user.
  final double totalSpent;

  /// Current wallet balance of the user.
  final double walletBalance;

  /// Date when the user joined (formatted string).
  final String joinedAt;

  const AdminUserItem({
    required this.id, required this.username, required this.email,
    required this.phone, required this.isApproved,
    required this.bookingCount, required this.totalSpent,
    required this.walletBalance, required this.joinedAt,
  });

  @override
  List<Object?> get props => [id, username, isApproved];
}

/// Detailed information about a user for admin view.
class AdminUserDetail extends Equatable {
  /// Unique identifier of the user.
  final int id;

  /// Username of the user.
  final String username;

  /// Email address of the user.
  final String email;

  /// Phone number of the user (optional).
  final String? phone;

  /// Whether the user account is approved.
  final bool isApproved;

  /// Date when the user joined (formatted string).
  final String joinedAt;

  /// Current wallet balance.
  final double walletBalance;

  /// Currency code for the wallet.
  final String currency;

  /// Total amount spent by the user.
  final double totalSpent;

  /// Total number of bookings made.
  final int bookingCount;

  /// List of user's bookings (as maps).
  final List<Map<String, dynamic>> bookings;

  /// List of user's payments (as maps).
  final List<Map<String, dynamic>> payments;

  /// List of user's transactions (as maps).
  final List<Map<String, dynamic>> transactions;

  const AdminUserDetail({
    required this.id, required this.username, required this.email,
    this.phone, required this.isApproved, required this.joinedAt,
    required this.walletBalance, required this.currency,
    required this.totalSpent, required this.bookingCount,
    required this.bookings, required this.payments, required this.transactions,
  });

  @override
  List<Object?> get props => [id, username, isApproved];
}

/// Represents a booking item for admin management.
class AdminBookingItem extends Equatable {
  /// Unique identifier of the booking.
  final int id;

  /// ID of the user who made the booking.
  final int userId;

  /// Username of the user who made the booking.
  final String username;

  /// ID of the club where the booking is made.
  final int clubId;

  /// Name of the club.
  final String clubName;

  /// Start time of the booking.
  final DateTime startTime;

  /// Duration of the booking in hours.
  final double durationHours;

  /// Number of computers booked.
  final int computersBooked;

  /// Total price of the booking.
  final double totalPrice;

  /// Status of the booking (e.g., ACTIVE, COMPLETED).
  final String status;

  /// Payment method used (optional).
  final String? paymentMethod;

  /// Payment status (optional).
  final String? paymentStatus;

  /// Date and time when the booking was created.
  final DateTime createdAt;

  const AdminBookingItem({
    required this.id, required this.userId, required this.username,
    required this.clubId, required this.clubName,
    required this.startTime, required this.durationHours,
    required this.computersBooked, required this.totalPrice,
    required this.status, this.paymentMethod, this.paymentStatus,
    required this.createdAt,
  });

  /// Calculates the end time of the booking based on start time and duration.
  DateTime get endTime => startTime.add(Duration(minutes: (durationHours * 60).round()));

  @override
  List<Object?> get props => [id, status];
}

/// Represents a payment item for admin management.
class AdminPaymentItem extends Equatable {
  /// Unique identifier of the payment.
  final int id;

  /// ID of the user who made the payment.
  final int userId;

  /// Username of the user.
  final String username;

  /// ID of the booking associated with the payment.
  final int bookingId;

  /// Name of the club where the booking was made.
  final String clubName;

  /// Amount of the payment.
  final double amount;

  /// Payment method used.
  final String method;

  /// Status of the payment.
  final String status;

  /// Date and time when the payment was created.
  final DateTime createdAt;

  const AdminPaymentItem({
    required this.id, required this.userId, required this.username,
    required this.bookingId, required this.clubName,
    required this.amount, required this.method, required this.status,
    required this.createdAt,
  });

  @override
  List<Object?> get props => [id, status];
}

/// Represents an active or upcoming session at a club.
class ClubSessionItem extends Equatable {
  /// ID of the booking associated with this session.
  final int bookingId;

  /// ID of the user who booked the session.
  final int userId;

  /// Username of the user.
  final String username;

  /// Number of computers booked for this session.
  final int computersBooked;

  /// Start time of the session.
  final DateTime startTime;

  /// End time of the session.
  final DateTime endTime;

  /// Remaining minutes until the session ends.
  final double remainingMinutes;

  /// Total price of the session (optional).
  final double? totalPrice;

  /// Status of the session.
  final String status;

  const ClubSessionItem({
    required this.bookingId, required this.userId, required this.username,
    required this.computersBooked, required this.startTime,
    required this.endTime, required this.remainingMinutes,
    this.totalPrice, required this.status,
  });

  @override
  List<Object?> get props => [bookingId, status, remainingMinutes];
}

/// Represents session information for a specific club.
class ClubSessions extends Equatable {
  /// Unique identifier of the club.
  final int clubId;

  /// Name of the club.
  final String clubName;

  /// Total number of computers in the club.
  final int totalComputers;

  /// List of currently active sessions.
  final List<ClubSessionItem> activeSessions;

  /// List of upcoming sessions.
  final List<ClubSessionItem> upcomingSessions;

  /// Number of available computers.
  final int availableComputers;

  const ClubSessions({
    required this.clubId, required this.clubName,
    required this.totalComputers, required this.activeSessions,
    required this.upcomingSessions, required this.availableComputers,
  });

  @override
  List<Object?> get props => [clubId, activeSessions.length];
}

/// Represents revenue information for a specific club.
class ClubRevenue extends Equatable {
  /// Unique identifier of the club.
  final int clubId;

  /// Name of the club.
  final String clubName;

  /// Total revenue generated by the club.
  final double totalRevenue;

  /// Total number of sessions held.
  final int totalSessions;

  /// Number of currently active sessions.
  final int activeSessions;

  /// List of revenue data by day.
  final List<RevenueByDay> revenueByDay;

  /// List of recent sessions.
  final List<ClubSessionItem> recentSessions;

  const ClubRevenue({
    required this.clubId, required this.clubName,
    required this.totalRevenue, required this.totalSessions,
    required this.activeSessions, required this.revenueByDay,
    required this.recentSessions,
  });

  @override
  List<Object?> get props => [clubId, totalRevenue];
}
